# Generated by Django 5.1.1 on 2024-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foryou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
